Repository readmeio/api-explorer, pull requests merged in 2019-12, with the labels that each got.

#397 Upgrading @readme/eslint-config to 1.7.0
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-logs/__tests__/index.test.jsx
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/syntax-highlighter/package-lock.json
  packages/syntax-highlighter/package.json
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: dependencies

#220 App selections should update current auth states
  example/bundle-hub2.css
  example/src/Demo.jsx
  example/swagger-files/multiple-securities.json
  packages/api-explorer/__tests__/AuthBox.test.jsx
  packages/api-explorer/__tests__/fixtures/multiple-securities/oas.json
  packages/api-explorer/__tests__/lib/get-auth.test.js
  packages/api-explorer/__tests__/lib/is-auth-ready.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/src/AuthBox.jsx
  packages/api-explorer/src/AuthBox/index.jsx
  packages/api-explorer/src/AuthBox/style.scss
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/PathUrl.jsx
  packages/api-explorer/src/SecurityInput.jsx
  packages/api-explorer/src/index.jsx
  packages/api-explorer/src/lib/get-auth.js
  packages/api-explorer/src/security-input-types/Basic.jsx
  packages/api-logs/package.json
  scripts/update-example-swagger-files.js
Labels: bug, enhancement

#402 Updating the oas dependency to resolve a bug in JSON Schema sorting
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: bug

#404 Fixing a regression of additionalProperties keys not being editable
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/src/form-components/SchemaField.jsx
Labels: bug
