Repository readmeio/api-explorer, pull requests merged in 2019-08, with the labels that each got.

#245 Expanding our support for integer formats to a wider variety.
  example/swagger-files/types.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/api-explorer.css
  packages/api-explorer/package-lock.json
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/form-components/SchemaField.jsx
Labels: bug, enhancement

#246 Pass response schema descriptions through the Markdown parser
  packages/api-explorer/src/ResponseSchema.jsx
Labels: bug

#258 If we fail to render JSON, fallback to string rendering.
  example/swagger-files/response-schemas.json
  packages/api-explorer/__tests__/Example.test.jsx
  packages/api-explorer/__tests__/fixtures/string/oas.json
  packages/api-explorer/src/Example.jsx
Labels: bug

#252 Updating our react-jsonschema-form fork to the latest HEAD.
  example/swagger-files/additional-properties.json
  packages/api-explorer/package-lock.json
Labels: bug, dependencies

#269 Updating CodeMirror and adding support for a few new languages.
  example/bundle-hub2.css
  example/swagger-files/examples.json
  packages/api-explorer/__tests__/lib/generate-code-snippet.test.js
  packages/api-explorer/src/lib/generate-code-snippet.js
  packages/syntax-highlighter/codemirror.jsx
  packages/syntax-highlighter/modes.js
  packages/syntax-highlighter/package-lock.json
  packages/syntax-highlighter/package.json
  packages/syntax-highlighter/test/index.test.js
  packages/syntax-highlighter/test/uppercase.test.js
  packages/syntax-highlighter/uppercase.js
  packages/variable/package-lock.json
Labels: dependencies, enhancement

#259 If the explorer is disabled, ArrayField components should be addable but uneditable
  example/swagger-files/types.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/src/form-components/ArrayField.jsx
Labels: bug

#211 Add support for common parameters
  packages/api-explorer/__tests__/lib/parameters-to-json-schema.test.js
  packages/api-explorer/src/index.jsx
  packages/api-explorer/src/lib/parameters-to-json-schema.js
Labels: enhancement
