Repository readmeio/api-explorer, pull requests merged in 2020-06, with the labels that each got.

#720 chore(deps): upgrading @readme/oas-tooling
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: dependencies

#721 feat: validate oas on preview
  example/src/Demo.jsx
  example/src/SpecFetcher.jsx
  example/swagger-files/additional-properties.json
  example/swagger-files/auth-types.json
  example/swagger-files/boolean.json
  example/swagger-files/common-parameters.json
  example/swagger-files/empty-params.json
  example/swagger-files/endpoint-error-boundary.json
  example/swagger-files/excerpt-markdown.json
  example/swagger-files/gh-issue-157.json
  example/swagger-files/multiple-media-types.json
  example/swagger-files/multiple-securities.json
  example/swagger-files/parameters-with-refs.json
  example/swagger-files/polymorphism.json
  example/swagger-files/raw-body.json
  example/swagger-files/server-variables.json
  example/swagger-files/types.json
  example/swagger-files/x-headers.json
  package-lock.json
  package.json
Labels: enhancement

#722 test: start running unit tests against node 14
  .github/workflows/ci.yml
Labels: enhancement

#725 chore(deps-dev): upgrading @readme/eslint-config to the latest
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/index.jsx
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/http-status-codes/package-lock.json
  packages/http-status-codes/package.json
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/oas-to-har/src/lib/configure-security.js
  packages/oas-to-har/src/lib/remove-undefined-objects.js
  packages/syntax-highlighter/package-lock.json
  packages/syntax-highlighter/package.json
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: dependencies

#728 feat: add support for syntax highlighting more languages
  packages/markdown/components/Code/index.jsx
  packages/markdown/processor/parse/flavored/callout.js
  packages/syntax-highlighter/CONTRIBUTING.md
  packages/syntax-highlighter/README.md
  packages/syntax-highlighter/__tests__/__fixtures__/c#/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/c#/sample.csharp
  packages/syntax-highlighter/__tests__/__fixtures__/c++/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/c++/sample.cplusplus
  packages/syntax-highlighter/__tests__/__fixtures__/clojure/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/clojure/sample.clojure
  packages/syntax-highlighter/__tests__/__fixtures__/css/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/d/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/d/sample.d
  packages/syntax-highlighter/__tests__/__fixtures__/erlang/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/erlang/sample.erlang
  packages/syntax-highlighter/__tests__/__fixtures__/groovy/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/groovy/sample.groovy
  packages/syntax-highlighter/__tests__/__fixtures__/html/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/http/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/http/sample.http
  packages/syntax-highlighter/__tests__/__fixtures__/js/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/julia/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/julia/sample.julia
  packages/syntax-highlighter/__tests__/__fixtures__/kotlin/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/kotlin/sample.kotlin
  packages/syntax-highlighter/__tests__/__fixtures__/markdown/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/markdown/sample.markdown
  packages/syntax-highlighter/__tests__/__fixtures__/objc++/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/objc++/sample.objcpp
  packages/syntax-highlighter/__tests__/__fixtures__/objc/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/objc/sample.objc
  packages/syntax-highlighter/__tests__/__fixtures__/perl/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/perl/sample.perl
  packages/syntax-highlighter/__tests__/__fixtures__/powershell/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/powershell/sample.powershell
  packages/syntax-highlighter/__tests__/__fixtures__/python/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/python/sample.python
  packages/syntax-highlighter/__tests__/__fixtures__/ruby/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/ruby/sample.ruby
  packages/syntax-highlighter/__tests__/__fixtures__/rust/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/rust/sample.rust
  packages/syntax-highlighter/__tests__/__fixtures__/shell/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/shell/sample.shell
  packages/syntax-highlighter/__tests__/__fixtures__/typescript/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/typescript/sample.ts
  packages/syntax-highlighter/__tests__/__fixtures__/yaml/index.js
  packages/syntax-highlighter/__tests__/__fixtures__/yaml/sample.yaml
  packages/syntax-highlighter/__tests__/__snapshots__/index.test.js.snap
  packages/syntax-highlighter/__tests__/index.test.js
  packages/syntax-highlighter/canonical.js
  packages/syntax-highlighter/codemirror.jsx
  packages/syntax-highlighter/modes.js
  packages/syntax-highlighter/uppercase.js
Labels: enhancement

#714 Strip preceding dashes from anchor IDs.
  packages/markdown/processor/plugin/section-anchor-id.js
Labels: Markdown, bug

#764 Remove RDMD anchor dash sanitization.
  packages/markdown/processor/plugin/section-anchor-id.js
Labels: Markdown

#791 chore(deps-dev): upgrading @readme/eslint-config to 3.2.0
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/http-status-codes/package-lock.json
  packages/http-status-codes/package.json
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/syntax-highlighter/package-lock.json
  packages/syntax-highlighter/package.json
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: dependencies

#792 feat: addition of a new "node-simple" client language for our api sdk module
  example/bundle-hub2.css
  example/src/Demo.jsx
  example/src/SpecFetcher.jsx
  example/swagger-files/petstore.json
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/__tests__/lib/generate-code-snippet.test.js
  packages/api-explorer/__tests__/lib/get-auth.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/index.jsx
  packages/api-explorer/src/lib/generate-code-snippet.js
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
Labels: enhancement

#795 chore(deps): upgrading httpsnippet-client-api to 2.1.1
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: dependencies

#794 feat: adding support for cookies to oas-to-har
  example/swagger-files/cookies.json
  packages/oas-to-har/__tests__/__fixtures__/common-parameters.json
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/src/index.js
Labels: enhancement

#796 ci: dinking around with bundlewatch
  .github/workflows/bundlewatch.yml
  .github/workflows/ci.yml
  package.json
Labels: enhancement

#797 chore(deps): upgrading httpsnippet-client-api to resolve issues
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#798 chore(deps): upgrading @readme/oas-tooling and httpsnippet-client-api
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug

#799 chore(deps): extracting @readme/http-status-codes into its own repo
  README.md
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/http-status-codes/.eslintignore
  packages/http-status-codes/.eslintrc
  packages/http-status-codes/.jsinspectrc
  packages/http-status-codes/.npmignore
  packages/http-status-codes/.prettierignore
  packages/http-status-codes/LICENSE
  packages/http-status-codes/README.md
  packages/http-status-codes/__tests__/.eslintrc
  packages/http-status-codes/__tests__/index.test.js
  packages/http-status-codes/jest.config.js
  packages/http-status-codes/package-lock.json
  packages/http-status-codes/package.json
  packages/http-status-codes/src/index.js
Labels: dependencies

#767 SSR-ready bundle for the RDMD engine.
  packages/api-explorer/package-lock.json
  packages/markdown/dist/main.node.js
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/webpack.config.js
Labels: area:markdown, type:enhancement

#729 Fix various RDMD syntax edge cases for code tabs component.
  packages/api-logs/package-lock.json
  packages/markdown-magic/package-lock.json
  packages/markdown/__tests__/__snapshots__/flavored-parsers.test.js.snap
  packages/markdown/__tests__/flavored-parsers.test.js
  packages/markdown/package-lock.json
  packages/markdown/processor/parse/flavored/code-tabs.js
Labels: area:markdown, type:bug

#806 chore(deps-dev): swapping auto-changelog for conventional-changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: scope:dependency

#660 Enable block-level components in magic tables.
  packages/api-explorer/dist/index.js
  packages/api-explorer/src/block-types/Content.jsx
  packages/api-explorer/src/index.jsx
  packages/markdown/README.md
  packages/markdown/components/CodeTabs/style.scss
  packages/markdown/components/Table/style.scss
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/dist/main.node.js
  packages/markdown/index.js
  packages/markdown/options.json
  packages/markdown/processor/parse/magic-block-parser.js
  packages/markdown/styles/gfm.scss
Labels: area:markdown, type:enhancement

#807 fix: issue where application/x-www-form-urlencoded payloads weren't being handled properly
  example/swagger-files/formdata.json
  packages/api-explorer/__tests__/lib/generate-code-snippet.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
Labels: area:explorer, type:bug, type:refactor
