Repository readmeio/api-explorer, pull requests merged in 2020-10, with the labels that each got.

#964 chore(deps): upgrading @readme/syntax-highlighter to 10.0.0
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/ResponseBody.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/block-types/CodeElement.jsx
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency

#940 feat: operation level extensions
  example/swagger-files/extensions.json
  example/swagger-files/petstore.json
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/PathUrl.jsx
  packages/api-explorer/src/Response.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/form-components/ArrayField.jsx
  packages/api-explorer/src/form-components/BaseInput.jsx
  packages/api-explorer/src/form-components/DateTimeWidget.jsx
  packages/api-explorer/src/form-components/FileWidget.jsx
  packages/api-explorer/src/form-components/SelectWidget.jsx
  packages/api-explorer/src/form-components/TextareaWidget.jsx
  packages/api-explorer/src/form-components/URLWidget.jsx
  packages/oas-extensions/index.js
  packages/oas-to-har/src/index.js
Labels: type:enhancement

#966 chore: stop storing package dist files in source control
  package.json
  packages/api-explorer/.gitignore
  packages/api-explorer/dist/index.js
  packages/api-explorer/dist/index.js.LICENSE
  packages/api-explorer/dist/index.js.LICENSE.txt
  packages/api-logs/.gitignore
  packages/api-logs/dist/index.js
  packages/api-logs/dist/index.js.LICENSE
  packages/api-logs/dist/index.js.LICENSE.txt
  packages/variable/.gitignore
Labels: type:refactor

#969 feat: adding support for the `example` property on responses
  example/swagger-files/examples.json
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/ExampleTabs.test.jsx
  packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
  packages/api-explorer/__tests__/lib/create-code-shower.test.js
  packages/api-explorer/__tests__/lib/get-response-examples.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/ResponseTabs.jsx
  packages/api-explorer/src/lib/create-code-shower.js
  packages/api-explorer/src/lib/get-response-examples.js
  packages/api-explorer/src/lib/show-code-examples.js
  packages/api-explorer/src/lib/show-code-results.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug, type:enhancement

#980 fix: updating our rjsf fork to fix a bug with oneOf stateloss
  example/swagger-files/polymorphism.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: scope:dependency, type:bug

#983 chore: removing a heap of unused oas-form packages
  packages/oas-form/package-lock.json
  packages/oas-form/package.json
  packages/oas-form/webpack.config.dist.js
Labels: scope:dependency

#984 fix: don't set an undefined format on the schema if we don't recognize it
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/__fixtures__/polymorphism/oas.json
  packages/api-explorer/src/form-components/SchemaField.jsx
Labels: type:bug

#985 chore(deps): upgrading `@readme/oas-tooling` to fix a flattenSchema bug
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug

#986 chore(deps): upgrading @readme/markdown to hide code copy buttons
  packages/api-explorer/__tests__/form-components/DescriptionField.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
  packages/api-explorer/src/block-types/Content.jsx
  packages/api-explorer/src/form-components/DescriptionField.jsx
Labels: scope:dependency, type:bug

#987 fix: bugs with processing examples
  CHANGELOG.md
  example/swagger-files/examples.json
  packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
  packages/api-explorer/__tests__/lib/get-response-examples.test.js
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/lib/get-response-examples.js
Labels: type:bug

#988 feat: swapping request module node samples with node-fetch
  packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.js
Labels: scope:dependency, type:enhancement

#989 fix: issue in node-simple snippets where basic auth wasn't decoded
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug

#998 chore(deps): swapping `@readme/oas-tooling` for `oas`
  packages/api-explorer/__tests__/AuthBox.test.jsx
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/ExampleTabs.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/PathUrl.test.jsx
  packages/api-explorer/__tests__/Response.test.jsx
  packages/api-explorer/__tests__/ResponseBody.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseSchema.test.jsx
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/__tests__/ResponseTabs.test.jsx
  packages/api-explorer/__tests__/lib/get-auth.test.js
  packages/api-explorer/__tests__/lib/get-response-examples.test.js
  packages/api-explorer/__tests__/lib/is-auth-ready.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/AuthBox/index.jsx
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/PathUrl.jsx
  packages/api-explorer/src/Response.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
  packages/api-explorer/src/ResponseTabs.jsx
  packages/api-explorer/src/lib/get-response-examples.js
  packages/oas-to-har/README.md
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/oas-to-snippet/README.md
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency

#1000 feat: set default javascript target to use fetch instead of xhr
  packages/oas-to-snippet/src/index.js
Labels: type:enhancement

#999 fix: updating the ResponseSchemaBody for the async flattenSchema changes
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/ResponseSchemaBody.jsx
  packages/markdown-magic/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug, type:refactor

#958 feat: tutorials-integration
  .github/workflows/bundlewatch.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  example/index.html
  example/src/Demo.jsx
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/index.jsx
  packages/api-explorer/style/main.scss
  packages/api-logs/package.json
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/oas-form/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: type:enhancement

#1004 chore: remove unnecessary stringification from node-fetch snippets
  package-lock.json
  package.json
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency

#1014 fix: regression in focus being lost when editing inputs in arrays
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/src/Params.jsx
  packages/oas-extensions/index.js
Labels: type:bug

#1005 chore: pinning react and react-dom across every dependency
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/webpack.config.js
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/api-logs/webpack.config.js
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/oas-extensions/package.json
  packages/oas-form/package-lock.json
  packages/oas-form/package.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/variable/package-lock.json
  packages/variable/package.json
  packages/variable/webpack.config.js
Labels: scope:dependency, type:refactor

#1016 chore(deps): upgrading `@readme/syntax-highlighter`
  package-lock.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:enhancement

#1015 fix: consumption
  packages/api-explorer/src/Doc.jsx
  packages/oas-to-snippet/src/index.js
  packages/oas-to-snippet/src/supportedLanguages.js
Labels: type:bug, type:enhancement
