Repository readmeio/api-explorer, pull requests merged in 2020-04, with the labels that each got.

#579 chore(markdown): Extract css build for SSRs
  package.json
  packages/markdown/README.md
  packages/markdown/__tests__/__snapshots__/index.test.js.snap
  packages/markdown/__tests__/components.test.js
  packages/markdown/components/Anchor.jsx
  packages/markdown/components/Callout/index.jsx
  packages/markdown/components/Callout/style.scss
  packages/markdown/components/CodeTabs/index.jsx
  packages/markdown/components/Heading/index.jsx
  packages/markdown/components/Heading/style.scss
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/dist/main.js.LICENSE.txt
  packages/markdown/index.js
  packages/markdown/options.json
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/processor/parse/flavored/callout.js
  packages/markdown/processor/parse/magic-block-parser.js
  packages/markdown/styles/gfm.scss
  packages/markdown/webpack.config.js
  packages/markdown/webpack.prod.js
Labels: bug, enhancement

#586 fix: if we have a value property in an example, return that
  example/swagger-files/examples.json
  packages/api-explorer/__tests__/lib/create-code-shower.test.js
  packages/api-explorer/src/lib/create-code-shower.js
Labels: bug

#587 chore(deps): upgrading @readme/oas-tooling to 3.1.7
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#589 chore(deps): upgrading @readme/react-jsonschema-form" to 1.1.5
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: bug, dependencies

#588 fix: refactoring when we're converting params to json schema
  packages/api-explorer/src/Params.jsx
Labels: bug

#590 chore(deps): upgrading @readme/oas-tooling to 3.1.8
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#599 fix: bug where responses with multiple examples weren't rendered properly
  packages/api-explorer/__tests__/lib/create-code-shower.test.js
  packages/api-explorer/src/lib/create-code-shower.js
Labels: bug

#600 fix: if an OAS has an empty examples object, don't parse it
  packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
  packages/api-explorer/__tests__/lib/create-code-shower.test.js
  packages/api-explorer/src/lib/create-code-shower.js
Labels: bug

#601 RDMD Feedback Fixes (2)
  packages/markdown/README.md
  packages/markdown/__tests__/__snapshots__/index.test.js.snap
  packages/markdown/__tests__/__snapshots__/magic-block-parser.test.js.snap
  packages/markdown/__tests__/components.test.js
  packages/markdown/__tests__/index.test.js
  packages/markdown/__tests__/magic-block-parser.test.js
  packages/markdown/components/Callout/index.jsx
  packages/markdown/components/Callout/style.scss
  packages/markdown/components/HTMLBlock.jsx
  packages/markdown/components/Table.jsx
  packages/markdown/components/index.js
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/index.js
  packages/markdown/package-lock.json
  packages/markdown/processor/parse/compact-headings.js
  packages/markdown/processor/parse/index.js
  packages/markdown/processor/parse/magic-block-parser.js
Labels: bug, enhancement

#602 fix: issues preventing people from upgrading off our legacy explorer
  packages/api-explorer/__tests__/lib/upgrade-legacy-responses.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/src/PathUrl.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/lib/generate-code-snippet.js
  packages/api-explorer/src/lib/upgrade-legacy-responses.js
  packages/markdown-magic/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug

#603 RDMD Feedback Fixes (3)
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown/__tests__/__snapshots__/index.test.js.snap
  packages/markdown/components/Callout/style.scss
  packages/markdown/components/CodeTabs/style.scss
  packages/markdown/components/Table/index.jsx
  packages/markdown/components/Table/style.scss
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/index.js
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/styles/components.scss
  packages/markdown/styles/gfm.scss
  packages/markdown/styles/main.scss
Labels: bug, dependencies, enhancement

#604 chore(deps): upgrading @readme/oas-tooling to 3.1.10
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#606 fix: cases where markdown headers dont have content
  packages/markdown-magic/components/Heading.jsx
Labels: bug

#607 RDMD Feedback Fixes (4)
  packages/api-explorer/package-lock.json
  packages/markdown-magic/package-lock.json
  packages/markdown/__tests__/__snapshots__/components.test.js.snap
  packages/markdown/__tests__/__snapshots__/index.test.js.snap
  packages/markdown/__tests__/__snapshots__/magic-block-parser.test.js.snap
  packages/markdown/components/CodeTabs/index.jsx
  packages/markdown/components/Image/index.jsx
  packages/markdown/components/Image/style.scss
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/processor/parse/magic-block-parser.js
  packages/markdown/styles/components.scss
  packages/markdown/styles/gfm.scss
  packages/oas-to-har/package-lock.json
Labels: bug, enhancement

#618 fix: legacy api upgrade issues
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#643 feat: adding support for a handful of language highlight aliases
  packages/syntax-highlighter/__tests__/__snapshots__/index.test.js.snap
  packages/syntax-highlighter/__tests__/index.test.js
  packages/syntax-highlighter/codemirror.jsx
  packages/syntax-highlighter/modes.js
Labels: bug, enhancement

#632 RDMD Next
  packages/api-explorer/dist/index.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/src/index.jsx
  packages/api-explorer/style/markdown-overrides.scss
  packages/markdown-magic/package-lock.json
  packages/markdown/__tests__/__snapshots__/components.test.js.snap
  packages/markdown/__tests__/__snapshots__/flavored-parsers.test.js.snap
  packages/markdown/__tests__/__snapshots__/index.test.js.snap
  packages/markdown/__tests__/components.test.js
  packages/markdown/__tests__/flavored-parsers.test.js
  packages/markdown/__tests__/index.test.js
  packages/markdown/__tests__/magic-block-parser.test.js
  packages/markdown/components/Callout/style.scss
  packages/markdown/components/Code.jsx
  packages/markdown/components/Code/index.jsx
  packages/markdown/components/Code/style.scss
  packages/markdown/components/CodeTabs/style.scss
  packages/markdown/components/Image/index.jsx
  packages/markdown/components/Image/style.scss
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/index.js
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/processor/parse/flavored/callout.js
  packages/markdown/processor/parse/flavored/code-tabs.js
  packages/markdown/processor/parse/magic-block-parser.js
  packages/markdown/processor/plugin/section-anchor-id.js
  packages/markdown/styles/components.scss
  packages/markdown/styles/gfm.scss
Labels: Markdown

#645 style(markdown): adjust lightbox img width
  packages/markdown/components/Image/style.scss
Labels: bug

#646 Add button to open up viewed spec file
  example/src/ApiList.jsx
  example/src/SpecFetcher.jsx
Labels: enhancement

#648 fix: filter out nullish arrays from generated HAR objects
  packages/oas-to-har/__tests__/lib/remove-undefined-objects.test.js
  packages/oas-to-har/src/lib/remove-undefined-objects.js
Labels: bug

#650 style(markdown): pull CSS from readme
  packages/markdown/components/Code/style.scss
Labels: bug

#655 chore(deps): upgrading @readme/oas-tooling to 3.3.3
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug

#658 chore(deps): upgrading @readme/oas-tooling to 3.3.4
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: bug, dependencies

#657 fix(markdown): support iframe magic embeds
  packages/markdown/__tests__/__snapshots__/magic-block-parser.test.js.snap
  packages/markdown/components/Embed.jsx
  packages/markdown/dist/main.css
  packages/markdown/dist/main.js
  packages/markdown/index.js
  packages/markdown/processor/parse/magic-block-parser.js
Labels: Markdown, enhancement

#654 Fix newlines in tabbed codeblocks
  packages/markdown/__tests__/__snapshots__/flavored-parsers.test.js.snap
  packages/markdown/__tests__/flavored-parsers.test.js
  packages/markdown/processor/parse/flavored/code-tabs.js
Labels: Markdown, bug

#659 Fix RDMD callout titles... (AGAIN 🎩)
  packages/markdown/__tests__/__snapshots__/components.test.js.snap
  packages/markdown/components/Callout/index.jsx
Labels: bug

#663 chore(deps): upgrading @readme/oas-tooling to 3.3.5
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: bug, dependencies
