Repository readmeio/api-explorer, pull requests merged in 2020-02, with the labels that each got.

#471 feat: setting a custom header for all "Try It" requests
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
Labels: enhancement

#472 fix: setting `x-readme-api-explorer` instead of a custom UA
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
Labels: bug

#473 feat: importing @readme/emojis in the markdown processor
  package.json
  packages/api-explorer/.eslintignore
  packages/markdown/emojis.js
  packages/markdown/gemoji-parser.js
  packages/markdown/package-lock.json
  packages/markdown/package.json
Labels: enhancement

#479 Support for legacy manual API multi-example, non-JSON responses
  example/swagger-files/examples.json
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/src/ResponseExample.jsx
Labels: bug

#484 fix: edge case where Content-Type could sometimes be doubled up
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/src/index.js
Labels: bug

#483 Put params before logs
  packages/api-explorer/src/Doc.jsx
Labels: enhancement

#485 chore(deps): swapping oas for @readme/oas-tooling
  packages/api-explorer/__tests__/AuthBox.test.jsx
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/ExampleTabs.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/PathUrl.test.jsx
  packages/api-explorer/__tests__/Response.test.jsx
  packages/api-explorer/__tests__/ResponseBody.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseSchema.test.jsx
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/__tests__/ResponseTabs.test.jsx
  packages/api-explorer/__tests__/lib/create-code-shower.test.js
  packages/api-explorer/__tests__/lib/generate-code-snippet.test.js
  packages/api-explorer/__tests__/lib/get-auth.test.js
  packages/api-explorer/__tests__/lib/is-auth-ready.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/AuthBox/index.jsx
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/PathUrl.jsx
  packages/api-explorer/src/Response.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
  packages/api-explorer/src/ResponseTabs.jsx
  packages/api-explorer/src/lib/create-code-shower.js
  packages/api-logs/package.json
  packages/markdown/package.json
  packages/oas-to-har/README.md
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/syntax-highlighter/package.json
  packages/variable/package.json
Labels: dependencies

#493 fix: downgrading datetime inputs to simple text inputs
  example/swagger-files/types.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/ResponseExample.jsx
Labels: bug

#494 chore(deps): upgrading @readme/oas-tooling to 2.1.0
  example/swagger-files/empty-params.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#496 chore(deps): upgrading @readme/oas-tooling to 2.1.1
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: dependencies
