Repository readmeio/api-explorer, pull requests merged in 2020-12, with the labels that each got.

#1066 fix: dont fetch logs for users who aren't logged in
  packages/api-logs/__tests__/index.test.jsx
  packages/api-logs/index.jsx
Labels: type:bug

#1079 fix: issues with the new json editor
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
Labels: type:bug

#1082 fix(api-explorer): fix legacy status ranges (4XX, etc)
  packages/api-explorer/__tests__/lib/upgrade-legacy-responses.test.js
  packages/api-explorer/src/lib/upgrade-legacy-responses.js
Labels: type:bug

#1080 chore(deps): move variable to peerdep
  packages/api-explorer/package.json
  packages/api-explorer/webpack.config.js
Labels: scope:dependency

#1081 fix: issue where changing response schemas wouldn't always update the component
  packages/api-explorer/src/ResponseSchema.jsx
Labels: type:bug

#1083 chore: deplatforming @readme/markdown-magic from this repo
  README.md
  package-lock.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/index.jsx
  packages/markdown-magic/.eslintignore
  packages/markdown-magic/.eslintrc
  packages/markdown-magic/.gitignore
  packages/markdown-magic/.npmignore
  packages/markdown-magic/.prettierignore
  packages/markdown-magic/GlossaryItem.jsx
  packages/markdown-magic/LICENSE
  packages/markdown-magic/README.md
  packages/markdown-magic/__tests__/.eslintrc
  packages/markdown-magic/__tests__/GlossaryItem.test.jsx
  packages/markdown-magic/__tests__/__snapshots__/index.test.js.snap
  packages/markdown-magic/__tests__/gemoji-parser.test.js
  packages/markdown-magic/__tests__/index.test.js
  packages/markdown-magic/__tests__/variable-parser.test.js
  packages/markdown-magic/components/Anchor.jsx
  packages/markdown-magic/components/Code.jsx
  packages/markdown-magic/components/Heading.jsx
  packages/markdown-magic/components/Table.jsx
  packages/markdown-magic/contexts/BaseUrl.js
  packages/markdown-magic/contexts/GlossaryTerms.js
  packages/markdown-magic/gemoji-parser.js
  packages/markdown-magic/index.js
  packages/markdown-magic/jest.config.js
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown-magic/variable-parser.js
Labels: scope:dependency, type:refactor

#1091 chore(deps): upgrading @readme/syntax-highlighter to 10.4.1
  package-lock.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency

#1094 revert: "feat: flipping the order of data in the response schema component"
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
Labels: type:bug

#1096 fix: bug where it takes two clicks to get a code snippet to copy
  packages/api-explorer/__tests__/CopyCode.test.jsx
  packages/api-explorer/src/CopyCode.jsx
Labels: type:bug

#1095 refactor: use nanoid instead of shortid
  package-lock.json
  packages/oas-form/package-lock.json
  packages/oas-form/package.json
  packages/oas-form/src/components/fields/ArrayField.js
Labels: type:refactor

#1093 fix(tutorials): solving ux issues within tutorial modal
  example/src/Demo.jsx
  package-lock.json
  package.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/index.jsx
Labels: type:bug

#1108 style: upgrading @readme/eslint-config to v4
  package-lock.json
  package.json
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/__tests__/ResponseTabs.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
  packages/oas-form/package-lock.json
  packages/oas-form/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: scope:dependency

#1111 fix: regression in support for common parameters
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug

#1114 fix: making the json editor only be present on body parameters
  example/swagger-files/petstore.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/style/main.scss
Labels: type:bug
