Repository readmeio/api-explorer, pull requests merged in 2020-09, with the labels that each got.

#930 chore: adding jsx transpilation to @readme/variable
  packages/variable/.gitignore
  packages/variable/package-lock.json
  packages/variable/package.json
  packages/variable/webpack.config.js
Labels: type:enhancement

#900 fix: bug where file names with parentheses aren't recognized as a valid data URI
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: type:bug

#951 chore(deps): upgrading @readme/react-jsonschema-form to 1.2.1
  example/swagger-files/cyclical-refs.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: scope:dependency, type:bug
