Repository readmeio/api-explorer, pull requests merged in 2020-03, with the labels that each got.

#506 fix: h1 anchor rendering
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/index.jsx
Labels: bug

#513 Configure Heroku review apps pipeline.
  Procfile
  package.json
Labels: exploration

#514 feat: splitting out our current markdown engine to a new package
  packages/markdown-magic/.eslintignore
  packages/markdown-magic/.eslintrc
  packages/markdown-magic/.gitignore
  packages/markdown-magic/.jsinspectrc
  packages/markdown-magic/.npmignore
  packages/markdown-magic/.prettierignore
  packages/markdown-magic/.prettierrc
  packages/markdown-magic/GlossaryItem.jsx
  packages/markdown-magic/LICENSE
  packages/markdown-magic/README.md
  packages/markdown-magic/__tests__/.eslintrc
  packages/markdown-magic/__tests__/GlossaryItem.test.jsx
  packages/markdown-magic/__tests__/__snapshots__/index.test.js.snap
  packages/markdown-magic/__tests__/gemoji-parser.test.js
  packages/markdown-magic/__tests__/index.test.js
  packages/markdown-magic/__tests__/variable-parser.test.js
  packages/markdown-magic/components/Anchor.jsx
  packages/markdown-magic/components/Code.jsx
  packages/markdown-magic/components/Heading.jsx
  packages/markdown-magic/components/Table.jsx
  packages/markdown-magic/contexts/BaseUrl.js
  packages/markdown-magic/contexts/GlossaryTerms.js
  packages/markdown-magic/example.js
  packages/markdown-magic/gemoji-parser.js
  packages/markdown-magic/index.js
  packages/markdown-magic/jest.config.js
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown-magic/variable-parser.js
Labels: dependencies

#517 feat: improved error messaging functionality
  example/src/Demo.jsx
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/src/BoundaryStackTrace.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/EndpointErrorBoundary.jsx
  packages/api-explorer/src/ErrorBoundary.jsx
  packages/api-explorer/src/index.jsx
  packages/api-explorer/style/ErrorBoundary.scss
  packages/api-explorer/style/main.scss
Labels: enhancement

#516 feat: backporting the legacy markdown engine to run alongside the new
  packages/api-explorer/__tests__/ResponseSchema.test.jsx
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/__tests__/block-types/ApiHeader.test.jsx
  packages/api-explorer/__tests__/block-types/CallOut.test.jsx
  packages/api-explorer/__tests__/block-types/Code.test.jsx
  packages/api-explorer/__tests__/block-types/Content.test.jsx
  packages/api-explorer/__tests__/block-types/Embed.test.jsx
  packages/api-explorer/__tests__/block-types/Html.test.jsx
  packages/api-explorer/__tests__/block-types/Image.test.jsx
  packages/api-explorer/__tests__/block-types/Parameters.test.jsx
  packages/api-explorer/__tests__/block-types/TextArea.test.jsx
  packages/api-explorer/__tests__/block-types/__snapshots__/CallOut.test.jsx.snap
  packages/api-explorer/__tests__/block-types/blocks.txt
  packages/api-explorer/__tests__/form-components/DescriptionField.test.jsx
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
  packages/api-explorer/src/block-types/ApiHeader.jsx
  packages/api-explorer/src/block-types/CallOut.jsx
  packages/api-explorer/src/block-types/Code.jsx
  packages/api-explorer/src/block-types/CodeElement.jsx
  packages/api-explorer/src/block-types/Content.jsx
  packages/api-explorer/src/block-types/Embed.jsx
  packages/api-explorer/src/block-types/Html.jsx
  packages/api-explorer/src/block-types/Image.jsx
  packages/api-explorer/src/block-types/Parameters.jsx
  packages/api-explorer/src/block-types/TextArea.jsx
  packages/api-explorer/src/form-components/DescriptionField.jsx
  packages/api-explorer/src/lib/parse-magic-blocks.js
Labels: enhancement

#518 chore(deps): upgrading react-waypoint to v9.0.2
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
Labels: dependencies

#520 feat: adding a handful of new status codes
  packages/http-status-codes/src/index.js
Labels: enhancement

#521 feat: implementing @readme/http-status-codes in the API Explorer
  packages/api-explorer/__tests__/lib/statuscodes.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/IconStatus.jsx
  packages/api-explorer/src/block-types/Code.jsx
  packages/api-explorer/src/lib/statuscodes.js
Labels: enhancement

#522 feat: adding a handful of unofficial http status codes
  packages/http-status-codes/src/index.js
Labels: enhancement

#523 fix: slightly reworking http-status-codes to be easier to use
  packages/api-explorer/src/IconStatus.jsx
  packages/api-explorer/src/block-types/Code.jsx
  packages/http-status-codes/__tests__/index.test.js
  packages/http-status-codes/src/index.js
Labels: enhancement

#525 fix: passing the onError callback into the Doc component
  packages/api-explorer/src/index.jsx
Labels: bug

#536 chore(deps): upgrading @readme/oas-tooling to 3.1.0 for min/max support
  example/swagger-files/types.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/__fixtures__/string/oas.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: dependencies, enhancement

#538 fix: resolving some quirks with the new error handling functionality
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/package.json
  packages/api-explorer/src/ErrorBoundary.jsx
Labels: bug

#541 fix: creating a custom UnsupportedField for RJSF to handle errors
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/ErrorBoundary.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/form-components/UnsupportedField.jsx
Labels: dependencies, enhancement

#542 feat: error codes are now unique to the error message they're for
  jest.config.js
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/src/ErrorBoundary.jsx
Labels: enhancement

#543 chore(deps): upgrading @readme/oas-tooling to 3.1.2
  example/swagger-files/types.json
  packages/api-explorer/example.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#545 fix: updating @readme/oas-tooling to 3.1.3
  packages/api-explorer/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#544 fix: setting a unique idPrefix for all forms to prevent dupe DOM IDs
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/src/Params.jsx
Labels: bug

#546 style: upgrading prettier to 2.0
  .prettierrc
  package-lock.json
  package.json
  packages/api-explorer/.prettierrc
  packages/api-explorer/__tests__/ExampleTabs.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseSchema.test.jsx
  packages/api-explorer/__tests__/ResponseTabs.test.jsx
  packages/api-explorer/__tests__/block-types/CallOut.test.jsx
  packages/api-explorer/__tests__/block-types/Image.test.jsx
  packages/api-explorer/__tests__/block-types/Parameters.test.jsx
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/ErrorBoundary.jsx
  packages/api-logs/.prettierrc
  packages/api-logs/__tests__/index.test.jsx
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/http-status-codes/.prettierrc
  packages/http-status-codes/package-lock.json
  packages/http-status-codes/package.json
  packages/markdown-magic/.prettierrc
  packages/markdown-magic/__tests__/gemoji-parser.test.js
  packages/markdown-magic/__tests__/variable-parser.test.js
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown/.prettierrc
  packages/markdown/__tests__/components.test.js
  packages/markdown/__tests__/gemoji-parser.test.js
  packages/markdown/__tests__/variable-parser.test.js
  packages/markdown/index.js
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/processor/compile/code-tabs.js
  packages/oas-to-har/.prettierrc
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/syntax-highlighter/.prettierrc
  packages/syntax-highlighter/package-lock.json
  packages/syntax-highlighter/package.json
  packages/variable/.prettierrc
  packages/variable/__tests__/index.test.jsx
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: dependencies

#547 chore(deps-dev): upgrading @readme/eslint-config to 2.0.0
  .prettierrc
  package-lock.json
  package.json
  packages/api-explorer/.prettierrc
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-logs/.prettierrc
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/http-status-codes/.prettierrc
  packages/http-status-codes/package-lock.json
  packages/http-status-codes/package.json
  packages/markdown-magic/.prettierrc
  packages/markdown-magic/package-lock.json
  packages/markdown-magic/package.json
  packages/markdown/.prettierrc
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/processor/compile/code-tabs.js
  packages/oas-to-har/.prettierrc
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/syntax-highlighter/.prettierrc
  packages/syntax-highlighter/package-lock.json
  packages/syntax-highlighter/package.json
  packages/variable/.prettierrc
  packages/variable/package-lock.json
  packages/variable/package.json
Labels: dependencies

#558 fix: using the appropriate markdown contexts when necessary
  packages/api-explorer/src/index.jsx
Labels: bug

#560 fix: support for repairing malformed array schemas
  example/swagger-files/types.json
  packages/api-explorer/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug, dependencies

#561 chore(deps): upgrading @readme/react-jsonschema-form to 1.1.4
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
Labels: bug, dependencies

#562 fix: removing some environmental exclusions of styles
  packages/markdown/components/Callout/index.jsx
  packages/markdown/components/CodeTabs/index.jsx
  packages/markdown/components/Heading/index.jsx
  packages/markdown/index.js
Labels: bug

#563 chore(deps): upgrading @readme/oas-tooling to 3.1.5
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
Labels: bug

#565 Fix @readme/markdown CSS imports.
  packages/markdown/package-lock.json
  packages/markdown/package.json
  packages/markdown/webpack.config.js
  packages/syntax-highlighter/codemirror.jsx
Labels: bug

#568 rdmd detail work
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/style/markdown-overrides.scss
  packages/markdown/__tests__/__snapshots__/components.test.js.snap
  packages/markdown/__tests__/__snapshots__/index.test.js.snap
  packages/markdown/__tests__/components.test.js
  packages/markdown/__tests__/flavored-compilers.test.js
  packages/markdown/__tests__/flavored-parsers.test.js
  packages/markdown/__tests__/index.test.js
  packages/markdown/__tests__/magic-block-parser.test.js
  packages/markdown/components/Embed.jsx
  packages/markdown/components/Heading/index.jsx
  packages/markdown/components/Heading/style.scss
  packages/markdown/components/Image.jsx
  packages/markdown/index.js
  packages/markdown/options.json
  packages/markdown/package-lock.json
  packages/markdown/processor/parse/flavored/callout.js
  packages/markdown/processor/parse/flavored/code-tabs.js
  packages/markdown/processor/parse/gemoji-parser.js
  packages/markdown/processor/parse/magic-block-parser.js
  packages/markdown/styles/gfm.overrides.scss
  packages/markdown/styles/gfm.scss
Labels: dependencies, enhancement
