Repository readmeio/api-explorer, pull requests merged in 2020-11, with the labels that each got.

#1028 style: removing jsinspect
  .jsinspectrc
  package-lock.json
  packages/api-explorer/.jsinspectrc
  packages/api-explorer/.npmignore
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-logs/.jsinspectrc
  packages/api-logs/.npmignore
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/markdown-magic/.jsinspectrc
  packages/markdown-magic/.npmignore
  packages/markdown-magic/package.json
  packages/oas-form/package-lock.json
  packages/oas-to-har/.jsinspectrc
  packages/oas-to-har/.npmignore
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/variable/.jsinspectrc
  packages/variable/.npmignore
  packages/variable/package.json
Labels: scope:dependency

#1027 feat: improved support for response examples
  package-lock.json
  packages/api-explorer/__tests__/AuthBox.test.jsx
  packages/api-explorer/__tests__/ExampleTabs.test.jsx
  packages/api-explorer/__tests__/PathUrl.test.jsx
  packages/api-explorer/__tests__/Response.test.jsx
  packages/api-explorer/__tests__/ResponseBody.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseTabs.test.jsx
  packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
  packages/api-explorer/__tests__/__fixtures__/example-results/swagger.json
  packages/api-explorer/__tests__/__fixtures__/petstore/swagger.json
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/__tests__/lib/get-response-examples.test.js
  packages/api-explorer/__tests__/lib/is-auth-ready.test.js
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/ExampleTabs.jsx
  packages/api-explorer/src/IconStatus.jsx
  packages/api-explorer/src/Response.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/ResponseTabs.jsx
  packages/api-explorer/src/lib/get-response-examples.js
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:enhancement

#1029 chore(deps): upgrading oas to 5.2.0
  package-lock.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/markdown-magic/package-lock.json
  packages/oas-form/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/variable/package-lock.json
Labels: scope:dependency

#1039 style: making the response example section scrollable
  packages/api-explorer/style/main.scss
Labels: type:bug

#1040 chore(deps): upgrading oas to 5.2.1
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/lib/content-type-is-json.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug, type:enhancement

#1044 fix(markdown): pinned callouts not rendering body
  package-lock.json
  packages/api-explorer/__tests__/block-types/Content.test.jsx
  packages/api-explorer/__tests__/block-types/__snapshots__/Content.test.jsx.snap
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/markdown-magic/package-lock.json
Labels: scope:dependency, type:bug

#1051 fix: reverting the markdown bump in #1044
  package-lock.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug

#1054 feat(api explorer): adding optional handler for auth group change
  packages/api-explorer/src/index.jsx
Labels: type:enhancement

#1055 chore: removing some dead code
  example/src/SpecFetcher.jsx
  jest.config.js
  packages/api-explorer/__tests__/__fixtures__/create-docs.js
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/__tests__/lib/construct-form-label.test.js
  packages/api-explorer/__tests__/lib/replace-vars.test.js
  packages/api-explorer/src/lib/construct-form-label.js
  packages/api-explorer/src/lib/replace-vars.js
  packages/markdown-magic/GlossaryItem.jsx
Labels: type:refactor

#1056 chore(oas-to-snippet): replace stringified request body with JSON.stringify and object
  package-lock.json
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/supportedLanguages.js
Labels: type:bug

#1064 refactor: splitting rdmd out as an external dep
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/webpack.config.js
Labels: type:refactor

#1041 chore(deps): upgrading oas to v6
  package-lock.json
  package.json
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/Response.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseSchema.test.jsx
  packages/api-explorer/package.json
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/oas-extensions/index.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency

#1050 feat: request body raw/json mode editor
  example/src/Demo.jsx
  jest.config.js
  package-lock.json
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/PathUrl.test.jsx
  packages/api-explorer/__tests__/ResponseSchema.test.jsx
  packages/api-explorer/__tests__/block-types/Code.test.jsx
  packages/api-explorer/__tests__/lib/content-type-is-json.test.js
  packages/api-explorer/package.json
  packages/api-explorer/src/CodeSample.jsx
  packages/api-explorer/src/CopyCode.jsx
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/PathUrl.jsx
  packages/api-explorer/src/ResponseBody.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/api-explorer/src/ResponseTabs.jsx
  packages/api-explorer/src/block-types/CodeElement.jsx
  packages/api-explorer/src/form-components/CodeEditor.jsx
  packages/api-explorer/src/index.jsx
  packages/api-explorer/src/lib/content-type-is-json.js
  packages/api-explorer/src/lib/parse-response.js
  packages/api-explorer/style/main.scss
  packages/markdown-magic/components/Code.jsx
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:enhancement

#1065 feat: flipping the order of data in the response schema component
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
Labels: type:enhancement

#1067 style: incorporating ui components in the preview site
  example/index.html
  example/src/ApiList.jsx
  example/src/Demo.jsx
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
Labels: type:enhancement

#1071 chore(deps): upgrading httpsnippet-client-api
  package-lock.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency
