Repository readmeio/api-explorer, pull requests merged in 2021-04, with the labels that each got.

#1249 feat: allowing for a HAR override to be passed in for snippet creation
  packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/src/index.js
Labels: type:enhancement

#1250 fix: fatal error where basic auth scheme might be missing
  packages/oas-to-har/__tests__/lib/configure-security.test.js
  packages/oas-to-har/src/lib/configure-security.js
Labels: type:bug

#1252 feat: making php a default language in the SAMPLES_LANGUAGES extension
  example/swagger-files/petstore.json
  packages/api-explorer/__tests__/__snapshots__/index.test.jsx.snap
  packages/oas-extensions/__tests__/index.test.js
  packages/oas-extensions/index.js
Labels: type:enhancement

#1253 fix: upgrading snippet dependencies to fix various issues
  package-lock.json
  packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug, type:enhancement

#1255 fix: removing undefined formData before processing it into postData
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/src/index.js
Labels: type:bug

#1256 feat: tunnel OAS url requests through our CORS proxy
  example/src/SpecFetcher.jsx
Labels: type:enhancement

#1257 feat: adding support for responses that don't have examples
  example/swagger-files/examples.json
  package-lock.json
  package.json
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/__fixtures__/example-results/oas.json
  packages/api-explorer/__tests__/__snapshots__/index.test.jsx.snap
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Response.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug, type:enhancement

#1259 feat: adding support for clojure, ocaml, and r languages
  example/bundle-hub2.css
  example/swagger-files/examples.json
  package-lock.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/supportedLanguages.js
Labels: type:enhancement

#1258 fix: enable code copy buttons
  example/swagger-files/excerpt-markdown.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/block-types/Content.jsx
Labels: javascript, type:bug

#1261 feat: adding support to oas-to-snippet for alternative language targets
  package-lock.json
  packages/oas-to-snippet/README.md
  packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.js
  packages/oas-to-snippet/src/supportedLanguages.js
Labels: type:enhancement

#1263 feat: exposing supported language target names in our export
  packages/oas-to-snippet/__tests__/__snapshots__/index.test.js.snap
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/src/supportedLanguages.js
Labels: type:enhancement
