Repository readmeio/api-explorer, pull requests merged in 2021-01, with the labels that each got.

#1129 chore(deps): bump ui to 1.17.6
  package-lock.json
  package.json
  packages/api-explorer/package.json
Labels: scope:dependency

#1124 test: building out a framework for testing readme manual apis
  example/bundle-hub2.css
  example/src/Demo.jsx
  example/src/SpecFetcher.jsx
  example/swagger-files/manual-api-logitech.json
  packages/api-explorer/src/index.jsx
  scripts/update-example-swagger-files.js
Labels: type:enhancement

#1110 feat: oas dereferencing and performance improvements
  .eslintrc
  example/src/Demo.jsx
  package-lock.json
  package.json
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/Response.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/ResponseSchemaBody.test.jsx
  packages/api-explorer/__tests__/ResponseTabs.test.jsx
  packages/api-explorer/__tests__/__snapshots__/index.test.jsx.snap
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/DocAsync.jsx
  packages/api-explorer/src/ErrorBoundary.jsx
  packages/api-explorer/src/Response.jsx
  packages/api-explorer/src/ResponseExample.jsx
  packages/api-explorer/src/ResponseSchema.jsx
  packages/api-explorer/src/ResponseSchemaBody.jsx
  packages/api-explorer/src/ResponseTabs.jsx
  packages/api-explorer/src/index.jsx
  packages/oas-form/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/variable/package-lock.json
Labels: exploration, type:perf, type:refactor

#1146 fix(api-explorer): prevent nulls from breaking operations
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/src/index.js
Labels: type:bug

#1155 feat: adding support for request examples
  example/swagger-files/petstore.json
  example/swagger-files/types.json
  package-lock.json
  package.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/style/main.scss
  packages/oas-form/__tests__/ArrayFieldTemplate_test.js
  packages/oas-form/__tests__/ArrayField_test.js
  packages/oas-form/__tests__/StringField_test.js
  packages/oas-form/__tests__/anyOf_test.js
  packages/oas-form/__tests__/uiSchema_test.js
  packages/oas-form/src/components/fields/ArrayField.js
  packages/oas-form/src/components/fields/StringField.js
  packages/oas-form/src/components/widgets/BaseInput.js
  packages/oas-form/src/types.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:enhancement

#1156 feat: introducing an interim loading screen in DocAsync
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/DocAsync.jsx
  packages/api-explorer/src/index.jsx
  packages/api-explorer/style/main.scss
  packages/oas-form/__tests__/utils_test.js
  packages/oas-form/src/utils.js
Labels: type:enhancement

#1159 fix: upgrade oas to fix a jsonpointer usage error
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug
