Repository readmeio/api-explorer, pull requests merged in 2021-03, with the labels that each got.

#1211 fix: bug with improperly placed discriminators
  packages/api-explorer/__tests__/__fixtures__/polymorphism/discriminators.json
  packages/api-explorer/__tests__/form-components/MultiSchemaField.test.jsx
  packages/api-explorer/src/form-components/MultiSchemaField.jsx
Labels: type:bug

#1220 feat: allow periods in variable regex
  packages/variable/__tests__/index.test.jsx
  packages/variable/index.jsx
Labels: javascript, type:bug

#1234 fix: bug where formData might be undefined with discrimators
  packages/api-explorer/__tests__/__fixtures__/polymorphism/discriminators.json
  packages/api-explorer/__tests__/form-components/MultiSchemaField.test.jsx
  packages/api-explorer/src/form-components/MultiSchemaField.jsx
Labels: type:bug

#1235 feat: adding support for storing our extensions in a `x-readme` object
  packages/api-explorer/__tests__/CodeSample.test.jsx
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/ResponseExample.test.jsx
  packages/api-explorer/__tests__/__fixtures__/multiple-securities/oas.json
  packages/api-explorer/__tests__/__fixtures__/parameters/common.json
  packages/api-explorer/__tests__/__fixtures__/petstore/oas.json
  packages/api-explorer/__tests__/__snapshots__/index.test.jsx.snap
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/index.jsx
  packages/oas-extensions/.eslintrc
  packages/oas-extensions/README.md
  packages/oas-extensions/__tests__/index.test.js
  packages/oas-extensions/index.js
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
Labels: type:enhancement, type:refactor

#1236 feat: adding new extensions for code and response samples
  packages/oas-extensions/__tests__/index.test.js
  packages/oas-extensions/index.js
Labels: type:enhancement

#1239 chore(deps): upgrading httpsnippet-client-api
  package-lock.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency

#1240 feat: adding a new `validateExtension` method to `oas-extensions`
  packages/oas-extensions/__tests__/index.test.js
  packages/oas-extensions/index.js
Labels: type:enhancement

#1241 feat: adding support for server variables into oas-to-har
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-extensions/package-lock.json
  packages/oas-to-har/README.md
  packages/oas-to-har/__tests__/__fixtures__/server-variables.json
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-har/src/index.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:enhancement

#1245 chore(deps): upgrading oas to 10.4.1
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-extensions/package-lock.json
  packages/oas-extensions/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:enhancement
