Repository readmeio/api-explorer, pull requests merged in 2021-02, with the labels that each got.

#1160 fix: ignore styling definitions on oas-reserved headers
  packages/oas-to-har/__tests__/lib/style-formatting/index.test.js
  packages/oas-to-har/src/lib/style-formatting/index.js
  packages/oas-to-har/src/lib/style-formatting/style-serializer.js
Labels: type:bug

#1166 fix: prevent code snippets from double encoding querystrings
  package-lock.json
  packages/oas-to-snippet/__tests__/index.test.js
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
  packages/oas-to-snippet/src/index.js
Labels: type:bug

#1165 Format useragent in simple terms
  jest.config.js
  lib/svgr-mock.js
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-logs/__tests__/index.test.jsx
  packages/api-logs/__tests__/utils.test.js
  packages/api-logs/assets/node-logo.svg
  packages/api-logs/assets/php-logo.svg
  packages/api-logs/assets/python-logo.svg
  packages/api-logs/assets/ruby-logo.svg
  packages/api-logs/index.jsx
  packages/api-logs/main.css
  packages/api-logs/package-lock.json
  packages/api-logs/package.json
  packages/api-logs/utils.js
  packages/api-logs/webpack.config.js
  packages/oas-form/package-lock.json
  webpack.common.js
  webpack.config.js
Labels: type:enhancement

#1170 fix: bug where we'd crash if `examples` was an empty object
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug

#1180 fix: missing operation schema exceptions
  example/swagger-files/manual-api-missingInOas.json
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: type:bug

#1178 test: moving oas-form unit tests over to using Jest
  jest.config.js
  package-lock.json
  packages/oas-form/__tests__/.eslintrc
  packages/oas-form/__tests__/ArrayFieldTemplate_test.js
  packages/oas-form/__tests__/ArrayField_test.js
  packages/oas-form/__tests__/BooleanField_test.js
  packages/oas-form/__tests__/DescriptionField_test.js
  packages/oas-form/__tests__/FieldTemplate_test.js
  packages/oas-form/__tests__/FormContext_test.js
  packages/oas-form/__tests__/Form_test.js
  packages/oas-form/__tests__/NullField_test.js
  packages/oas-form/__tests__/NumberField_test.js
  packages/oas-form/__tests__/ObjectFieldTemplate_test.js
  packages/oas-form/__tests__/ObjectField_test.js
  packages/oas-form/__tests__/SchemaField_test.js
  packages/oas-form/__tests__/StringField_test.js
  packages/oas-form/__tests__/TitleField_test.js
  packages/oas-form/__tests__/allOf_test.js
  packages/oas-form/__tests__/anyOf_test.js
  packages/oas-form/__tests__/const_test.js
  packages/oas-form/__tests__/mocha.opts
  packages/oas-form/__tests__/oneOf_test.js
  packages/oas-form/__tests__/setup-jsdom.js
  packages/oas-form/__tests__/test_utils.js
  packages/oas-form/__tests__/uiSchema_test.js
  packages/oas-form/__tests__/utils_test.js
  packages/oas-form/__tests__/validate_test.js
  packages/oas-form/__tests__/withTheme_test.js
  packages/oas-form/jest.config.js
  packages/oas-form/jest.setup.js
  packages/oas-form/package-lock.json
  packages/oas-form/package.json
Labels: type:refactor

#1182 chore(deps): upgrading oas to 10.0.4
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug, type:enhancement

#1181 feat: start exposing `pattern` attributes in schemas
  example/swagger-files/types.json
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/__fixtures__/string/oas.json
  packages/oas-form/src/components/widgets/BaseInput.js
Labels: type:enhancement

#1187 fix: upgrading httpsnippet to fix a ruby ssl exploit
  package-lock.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, security

#1157 Add support for discriminators
  example/swagger-files/discriminators.json
  package-lock.json
  packages/api-explorer/.eslintrc
  packages/api-explorer/__tests__/__fixtures__/polymorphism/discriminators.json
  packages/api-explorer/__tests__/__fixtures__/polymorphism/oas.json
  packages/api-explorer/__tests__/__snapshots__/index.test.jsx.snap
  packages/api-explorer/__tests__/form-components/MultiSchemaField.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/form-components/MultiSchemaField.jsx
  packages/api-explorer/src/form-components/SchemaField.jsx
  packages/oas-form/__tests__/StringField_test.js
  packages/oas-form/src/components/fields/StringField.js
  packages/oas-form/src/components/widgets/SelectWidget.js
Labels: type:enhancement

#1190 fix: updating oas to fix a bug with shapeless allOf child schemas
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-form/package-lock.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency, type:bug

#1191 fix: update the prop type on `placeholder` to accept numbers
  packages/oas-form/src/components/widgets/BaseInput.js
Labels: type:bug

#1193 refactor: decoupling our ui library from the api explorer codebase
  example/src/Demo.jsx
  jest.config.js
  package-lock.json
  package.json
  packages/api-explorer/__tests__/Doc.test.jsx
  packages/api-explorer/__tests__/Params.test.jsx
  packages/api-explorer/__tests__/index.test.jsx
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/Doc.jsx
  packages/api-explorer/src/Params.jsx
  packages/api-explorer/src/index.jsx
Labels: type:refactor

#1179 perf: oas-form bloat reduction and bundle overhauls
  package-lock.json
  packages/api-explorer/__tests__/__snapshots__/index.test.jsx.snap
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/api-explorer/src/form-components/MultiSchemaField.jsx
  packages/api-explorer/src/form-components/SchemaField.jsx
  packages/api-explorer/webpack.config.js
  packages/api-explorer/webpack.prod.js
  packages/oas-form/.babelrc
  packages/oas-form/__tests__/ArrayField_test.js
  packages/oas-form/__tests__/BooleanField_test.js
  packages/oas-form/__tests__/Form_test.js
  packages/oas-form/__tests__/NullField_test.js
  packages/oas-form/__tests__/NumberField_test.js
  packages/oas-form/__tests__/ObjectField_test.js
  packages/oas-form/__tests__/SchemaField_test.js
  packages/oas-form/__tests__/StringField_test.js
  packages/oas-form/__tests__/anyOf_test.js
  packages/oas-form/__tests__/oneOf_test.js
  packages/oas-form/__tests__/test_utils.js
  packages/oas-form/__tests__/utils_test.js
  packages/oas-form/__tests__/validate_test.js
  packages/oas-form/__tests__/withTheme_test.js
  packages/oas-form/package-lock.json
  packages/oas-form/package.json
  packages/oas-form/src/components/ErrorList.js
  packages/oas-form/src/components/Form.js
  packages/oas-form/src/components/fields/ArrayField.js
  packages/oas-form/src/components/fields/BooleanField.js
  packages/oas-form/src/components/fields/MultiSchemaField.js
  packages/oas-form/src/components/fields/ObjectField.js
  packages/oas-form/src/components/fields/SchemaField.js
  packages/oas-form/src/components/fields/StringField.js
  packages/oas-form/src/components/widgets/BaseInput.js
  packages/oas-form/src/index.js
  packages/oas-form/src/types.js
  packages/oas-form/src/utils.js
  packages/oas-form/src/validate.js
  packages/oas-form/src/withTheme.js
  packages/oas-form/webpack.config.js
Labels: exploration, type:refactor

#1195 fix(oas-to-har): fix validation failures when using multiple json formats
  packages/oas-to-har/__tests__/index.test.js
  packages/oas-to-har/src/index.js
Labels: type:bug

#1196 fix: enabling useObjectBody on js fetch snippets
  packages/oas-to-snippet/src/supportedLanguages.js
Labels: type:bug

#1198 chore(deps): upgrading oas to 10.2.0
  package-lock.json
  package.json
  packages/api-explorer/package-lock.json
  packages/api-explorer/package.json
  packages/oas-to-har/package-lock.json
  packages/oas-to-har/package.json
  packages/oas-to-snippet/package-lock.json
  packages/oas-to-snippet/package.json
Labels: scope:dependency
